plugins {
    id 'architectury-plugin' version '3.5.166'
    id 'dev.architectury.loom' version '1.14.476' apply false
    id 'com.gradleup.shadow' version '8.3.6' apply false
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

architectury {
    minecraft = rootProject.minecraft_version
}

allprojects {
    version = rootProject.mod_version
    group = rootProject.maven_group

    repositories {
        if (rootProject.useLocalToucanLib.toBoolean()) {
            mavenLocal()
        }

        mavenCentral()
        maven {
            name = 'Architectury'
            url = 'https://maven.architectury.dev/'
        }
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        maven {
            name = 'Quilt'
            url = 'https://maven.quiltmc.org/repository/release/'
        }
        maven {
            name = 'TerraformersMC'
            url = 'https://maven.terraformersmc.com/releases/'
        }
        maven {
            name = 'Wisp Forest'
            url = 'https://maven.wispforest.io/releases/'
        }
        maven {
            name = 'JitPack'
            url = 'https://jitpack.io'
        }
        maven {
            name = 'Sinytra'
            url = 'https://maven.sinytra.org/'
        }
        maven {
            name = 'Kotlin for Forge'
            url = 'https://thedarkcolour.github.io/KotlinForForge/'
        }
        maven {
            name = 'NeoForge'
            url = 'https://maven.neoforged.net/releases/'
        }
        maven {
            name = 'ParchmentMC'
            url = 'https://maven.parchmentmc.org/'
        }
        maven {
            name = 'Modrinth'
            url = 'https://api.modrinth.com/maven'
            content {
                includeGroup 'maven.modrinth'
            }
        }
    }
}

subprojects {
    apply plugin: 'java-library'
    apply plugin: 'maven-publish'
    apply plugin: 'dev.architectury.loom'

    base {
        archivesName = "${rootProject.archives_base_name}-${project.name}-${rootProject.minecraft_version}"
    }

    java {
        toolchain.languageVersion = JavaLanguageVersion.of(rootProject.java_version.toInteger())
        withSourcesJar()
    }

    loom {
        silentMojangMappingsLicense()
    }

    dependencies {
        minecraft "com.mojang:minecraft:${rootProject.minecraft_version}"
        mappings loom.layered {
            officialMojangMappings()
            parchment("org.parchmentmc.data:parchment-${rootProject.parchment_minecraft_version}:${rootProject.parchment_mappings_version}@zip")
        }
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
        options.release = rootProject.java_version.toInteger()
    }

    publishing {
        publications {
            register('mavenJava', MavenPublication) {
                from components.java
            }
        }
        repositories {
            maven {
                url = rootProject.file('repo').toURI()
            }
        }
    }
}
