org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=false
org.gradle.caching=true
org.gradle.configuration-cache=false

# Template Properties
java_version=21
enabled_platforms=fabric,neoforge

# Minecraft Properties
minecraft_version=1.21.1
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

# Dependency Versions
architectury_version=13.0.8
fabric_loader_version=0.19.2
fabric_api_version=0.116.12+1.21.1
neo_version=21.1.215
modmenu_version=11.0.4
owo_fabric_version=0.12.15.4+1.21
owo_neoforge_version=0.12.15.1-beta.6+1.21

# ToucanLib
enable_toucanlib=true
useLocalToucanLib=false
toucanlib_version=0.3.1

# Loader Ranges
minecraft_version_range=[1.21.1]
loader_version_range=[1,)

## Mod Properties
mod_id=secondwind
mod_name=Second Wind!
mod_authors=jvn
mod_license=All Rights Reserved
mod_version=1.1.0
maven_group=com.jvn.secondwind
archives_base_name=secondwind
mod_description=A second-chance downed state mod inspired by Borderlands.
mod_display_url=https://modrinth.com/mod/Second-Wind-/
mod_issue_tracker=https://github.com/JevenDev/Second-Wind-/issues
