apply plugin: 'java-library'
apply plugin: 'maven-publish'
apply plugin: 'architectury-plugin'
apply plugin: 'dev.architectury.loom'

architectury {
    common(rootProject.enabled_platforms.split(','))
}

sourceSets.main.resources {
    srcDir('src/generated/resources')
    exclude('**/*.bbmodel')
    exclude('src/generated/**/.cache')
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
    modApi "dev.architectury:architectury:${rootProject.architectury_version}"

    if (rootProject.enable_toucanlib.toBoolean()) {
        def toucanlibDependency = rootProject.useLocalToucanLib.toBoolean()
                ? "com.jvn.toucanlib:toucanlib:${rootProject.toucanlib_version}"
                : "maven.modrinth:toucan:${rootProject.toucanlib_version}-fabric"
        modCompileOnly toucanlibDependency
    }

    testImplementation platform('org.junit:junit-bom:5.11.4')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}

tasks.named('processResources', ProcessResources).configure {
    var replaceProperties = [
            mod_name: rootProject.mod_name,
    ]
    inputs.properties replaceProperties

    filesMatching('pack.mcmeta') {
        expand replaceProperties
    }
}
